# Generated by Django 4.2.7 on 2026-02-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricetier',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_tiers', to='master_data.customertype'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.product'),
        ),
    ]
