# Generated by Django 4.2.7 on 2026-02-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
    ]
