# Generated by Django 4.2.7 on 2026-02-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productvariant_deleted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['deleted_at'], name='core_produc_deleted_d5465d_idx'),
        ),
    ]
