# Generated by Django 4.2.7 on 2026-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_core_produc_deleted_d5465d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='core_stockm_created_a48320_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='core_stockm_referen_2ec839_idx'),
        ),
    ]
