# Generated by Django 4.2.7 on 2026-02-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_stockmovement_core_stockm_created_a48320_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='core_batch_batch_n_c5ed7e_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='core_batch_expiry__7dbedc_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['deleted_at'], name='core_batch_deleted_a702b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='core_produc_name_be3252_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='core_produc_sku_a1eae6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='core_stockm_movemen_60f0ad_idx'),
        ),
    ]
