# Generated by Django 4.2.7 on 2026-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_batch_core_batch_batch_n_c5ed7e_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('base_price__gte', 0)), name='product_base_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('cost_price__gte', 0), ('cost_price__isnull', True), _connector='OR'), name='product_cost_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('stock_quantity__gte', 0)), name='product_stock_quantity_gte_0'),
        ),
    ]
