# Generated by Django 4.2.7 on 2026-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_product_base_price_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_alert_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before expiry to trigger alert'),
        ),
    ]
