# Generated by Django 4.2.7 on 2026-02-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit logs'},
        ),
    ]
