# Generated by Django 4.2.7 on 2026-02-05 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_alter_auditlog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit log archive',
                'verbose_name_plural': 'Audit log archives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='common_audi_created_5f768f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='common_audi_action_288430_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name'], name='common_audi_model_n_3fbf76_idx'),
        ),
        migrations.AddField(
            model_name='auditlogarchive',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlogarchive',
            index=models.Index(fields=['created_at'], name='common_audi_created_f51a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogarchive',
            index=models.Index(fields=['action'], name='common_audi_action_50baa6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogarchive',
            index=models.Index(fields=['model_name'], name='common_audi_model_n_a6541a_idx'),
        ),
    ]
