# Generated by Django 4.2.7 on 2026-02-04 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.salesorder')),
                ('return_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='master_data.returntype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='master_data.returnrequeststatus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Stock Restored', 'Stock Restored')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_processing', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_log', to='returns.returnrequest')),
            ],
            options={
                'verbose_name_plural': 'Return processing log',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('condition_notes', models.TextField(blank=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='core.product')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='master_data.returnreason')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['return_request', 'id'],
            },
        ),
    ]
