# Generated by Django 4.2.7 on 2026-02-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnprocessing',
            options={'ordering': ['-processed_at'], 'verbose_name': 'Return processing log', 'verbose_name_plural': 'Return processing log'},
        ),
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Return request', 'verbose_name_plural': 'Return requests'},
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='returns_ret_status__4d0c59_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['created_at'], name='returns_ret_created_a48112_idx'),
        ),
    ]
