# Generated by Django 4.2.7 on 2026-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order'], name='returns_ret_order_i_30fb33_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['deleted_at'], name='returns_ret_deleted_a6d97a_idx'),
        ),
    ]
