# Generated by Django 4.2.7 on 2026-02-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='return_to_stock',
            field=models.BooleanField(default=True, help_text='If checked, items will be added back to stock upon approval.'),
        ),
    ]
