# Generated by Django 4.2.7 on 2026-02-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_salesorder_order_type'),
        ('returns', '0004_returnitem_return_to_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_request_source', to='orders.salesorder', verbose_name='Replacement Order'),
        ),
    ]
