"""
Status code constants - avoid hard-coded strings across the codebase.
"""
# Order status codes
ORDER_PENDING = 'PENDING'
ORDER_CONFIRMED = 'CONFIRMED'
ORDER_DELIVERED = 'DELIVERED'
ORDER_PAID = 'PAID'
ORDER_CANCELLED = 'CANCELLED'

# Return request status codes
RETURN_PENDING = 'PENDING'
RETURN_APPROVED = 'APPROVED'
RETURN_REJECTED = 'REJECTED'
RETURN_COMPLETED = 'COMPLETED'

# Purchase order status codes
PURCHASE_PENDING = 'PENDING'
PURCHASE_ORDERED = 'ORDERED'
PURCHASE_RECEIVED = 'RECEIVED'
PURCHASE_CANCELLED = 'CANCELLED'

# Lead status codes (CRM)
LEAD_STATUS_NEW = 'NEW'
LEAD_STATUS_CONTACTED = 'CONTACTED'
LEAD_STATUS_SAMPLE_GIVEN = 'SAMPLE_GIVEN'
LEAD_STATUS_CONVERTED = 'CONVERTED'
LEAD_STATUS_LOST = 'LOST'

# Sample delivery status codes (CRM)
SAMPLE_STATUS_GIVEN = 'GIVEN'
SAMPLE_STATUS_RETURNED = 'RETURNED'
SAMPLE_STATUS_NOT_RETURNED = 'NOT_RETURNED'
