# Generated by Django 4.2.7 on 2026-02-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_batch_core_batch_batch_n_c5ed7e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_items_sold', models.PositiveIntegerField(default=0)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Sales Summary',
                'verbose_name_plural': 'Daily Sales Summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='reports_dai_date_ea064d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.product')),
            ],
            options={
                'verbose_name': 'Daily Inventory Snapshot',
                'verbose_name_plural': 'Daily Inventory Snapshots',
                'ordering': ['-date', 'product'],
                'indexes': [models.Index(fields=['date'], name='reports_dai_date_91ec79_idx'), models.Index(fields=['product'], name='reports_dai_product_7875e1_idx')],
                'unique_together': {('date', 'product')},
            },
        ),
    ]
