# Generated by Django 4.2.7 on 2026-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Payment Summary',
                'verbose_name_plural': 'Daily Payment Summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='reports_dai_date_c02412_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyExpenseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Expense Summary',
                'verbose_name_plural': 'Daily Expense Summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='reports_dai_date_d5be5e_idx')],
            },
        ),
    ]
