# Generated by Django 4.2.7 on 2026-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_address_customer_street_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='salesperson',
            options={'ordering': ['name'], 'verbose_name': 'Salesperson', 'verbose_name_plural': 'Salespeople'},
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, help_text='For Shop/Distributor - leave blank for Individual', max_length=100, verbose_name='Contact person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_name',
            field=models.CharField(blank=True, help_text='For Shop/Distributor - leave blank for Individual', max_length=200, verbose_name='Shop/Store name'),
        ),
    ]
