# Generated by Django 4.2.7 on 2026-02-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_shop_name_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.salesperson', verbose_name='Salesperson'),
        ),
    ]
