# Generated by Django 4.2.7 on 2026-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_salesperson_to_customer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['deleted_at'], name='customers_c_deleted_a9584a_idx'),
        ),
    ]
