# Generated by Django 4.2.7 on 2026-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_salesperson_deleted_at_alter_customer_deleted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customers_c_name_f018e2_idx'),
        ),
    ]
