# Generated by Django 4.2.7 on 2026-02-09 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_country_region_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_customer_customers_c_name_f018e2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed', max_digits=12, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='master_data.customertype', verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0, help_text='Days until payment due after delivery', verbose_name='Payment Terms (Days)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='master_data.township', verbose_name='Township'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesperson_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
