# Generated by Django 4.2.7 on 2026-02-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalespersonPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='Notes')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to='customers.salesperson')),
            ],
            options={
                'verbose_name': 'Salesperson phone number',
                'verbose_name_plural': 'Salesperson phone numbers',
            },
        ),
        migrations.CreateModel(
            name='CustomerPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer phone number',
                'verbose_name_plural': 'Customer phone numbers',
            },
        ),
    ]
