# Generated by Django 4.2.7 on 2026-02-05 04:43

from django.db import migrations, models
import django.db.models.deletion


def migrate_contact_type_to_fk(apps, schema_editor):
    """Migrate old CharField contact_type to ContactType FK."""
    ContactLog = apps.get_model('crm', 'ContactLog')
    ContactType = apps.get_model('master_data', 'ContactType')
    # Ensure default ContactTypes exist
    defaults = [
        ('PHONE', 'Phone', 'ဖုန်း', 1),
        ('VISIT', 'Visit', 'သွားရောက်တွေ့ဆုံ', 2),
        ('EMAIL', 'Email', 'အီးမေးလ်', 3),
        ('OTHER', 'Other', 'အခြား', 4),
    ]
    for code, name_en, name_my, sort_order in defaults:
        ContactType.objects.get_or_create(code=code, defaults={
            'name_en': name_en, 'name_my': name_my, 'sort_order': sort_order
        })
    for log in ContactLog.objects.all():
        code = getattr(log, 'contact_type_old', None) or 'PHONE'
        try:
            ct = ContactType.objects.get(code=code)
            log.contact_type_new = ct
            log.save()
        except ContactType.DoesNotExist:
            ct = ContactType.objects.first()
            if ct:
                log.contact_type_new = ct
                log.save()


def reverse_migrate(apps, schema_editor):
    """Reverse: copy FK back to char (not used in practice)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_contact_type_township'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='township',
            field=models.ForeignKey(blank=True, help_text='Location township (links to Region)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='master_data.township'),
        ),
        migrations.RenameField(
            model_name='contactlog',
            old_name='contact_type',
            new_name='contact_type_old',
        ),
        migrations.AddField(
            model_name='contactlog',
            name='contact_type_new',
            field=models.ForeignKey(help_text='Type of contact (from Master Data)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_logs', to='master_data.contacttype'),
        ),
        migrations.RunPython(migrate_contact_type_to_fk, reverse_migrate),
        migrations.RemoveField(
            model_name='contactlog',
            name='contact_type_old',
        ),
        migrations.RenameField(
            model_name='contactlog',
            old_name='contact_type_new',
            new_name='contact_type',
        ),
        migrations.AlterField(
            model_name='contactlog',
            name='contact_type',
            field=models.ForeignKey(help_text='Type of contact (from Master Data)', on_delete=django.db.models.deletion.PROTECT, related_name='contact_logs', to='master_data.contacttype'),
        ),
        migrations.AlterField(
            model_name='sampledelivery',
            name='status',
            field=models.CharField(choices=[('GIVEN', 'Given'), ('RETURNED', 'Returned'), ('NOT_RETURNED', 'Not Returned'), ('CONVERTED', 'Converted to Sale')], default='GIVEN', max_length=20),
        ),
    ]
