# Generated by Django 4.2.7 on 2026-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_type_township'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact log', 'verbose_name_plural': 'Contact logs'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='sampledelivery',
            options={'ordering': ['-given_at'], 'verbose_name': 'Sample delivery', 'verbose_name_plural': 'Sample deliveries'},
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(blank=True, help_text='For Shop/Distributor - leave blank for Individual', max_length=100, verbose_name='Contact person'),
        ),
        migrations.AddField(
            model_name='lead',
            name='shop_name',
            field=models.CharField(blank=True, help_text='For Shop/Distributor - leave blank for Individual', max_length=200, verbose_name='Shop/Store name'),
        ),
    ]
