# Generated by Django 4.2.7 on 2026-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_shop_name_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['deleted_at'], name='crm_lead_deleted_1073f9_idx'),
        ),
    ]
