# Generated by Django 4.2.7 on 2026-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='sampledelivery',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='sampledelivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='sampledelivery',
            index=models.Index(fields=['deleted_at'], name='crm_sampled_deleted_9cf8b0_idx'),
        ),
    ]
