# Generated by Django 4.2.7 on 2026-02-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contactlog_deleted_at_sampledelivery_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sampledelivery',
            name='crm_sampled_deleted_9cf8b0_idx',
        ),
    ]
