# Generated by Django 4.2.7 on 2026-02-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead_crm_lead_status_2c1bc7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='Notes')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead phone number',
                'verbose_name_plural': 'Lead phone numbers',
            },
        ),
    ]
