# Generated by Django 4.2.7 on 2026-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Purchase order', 'verbose_name_plural': 'Purchase orders'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['deleted_at'], name='purchasing__deleted_e6d2f6_idx'),
        ),
    ]
