# Generated by Django 4.2.7 on 2026-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_date'], name='purchasing__expecte_25fb06_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['reference_number'], name='purchasing__referen_4d214b_idx'),
        ),
    ]
