"""
Application-wide constants - pagination, limits, etc.
"""
# Pagination
PAGE_SIZE_ORDERS = 20
PAGE_SIZE_RETURNS = 20
PAGE_SIZE_PRODUCTS = 25
PAGE_SIZE_CUSTOMERS = 25

# List limits
LIMIT_RECENT_ORDERS = 10
LIMIT_RECENT_RETURNS = 5
LIMIT_RECENT_MOVEMENTS = 10
LIMIT_LOW_STOCK_DISPLAY = 15
LIMIT_EXPIRY_DAYS = 30
LIMIT_EXPIRY_URGENT_DAYS = 2
LIMIT_CUSTOMER_SEARCH = 10
LIMIT_STOCK_MOVEMENTS = 50
LIMIT_EXPORT_ROWS = 1000
LIMIT_AUDIT_LOG_DISPLAY = 500
LIMIT_AUDIT_LOG_EXPORT = 5000
