# Generated by Django 4.2.7 on 2026-02-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_companysetting_deliveryroute_promotion_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['code'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
    ]
