# Generated by Django 4.2.7 on 2026-02-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_contact_type_township'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_my', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AlterModelOptions(
            name='companysetting',
            options={'verbose_name': 'Company setting', 'verbose_name_plural': 'Company settings'},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Contact type', 'verbose_name_plural': 'Contact types'},
        ),
        migrations.AlterModelOptions(
            name='customertype',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Customer type', 'verbose_name_plural': 'Customer types'},
        ),
        migrations.AlterModelOptions(
            name='deliveryroute',
            options={'ordering': ['code'], 'verbose_name': 'Delivery route', 'verbose_name_plural': 'Delivery routes'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Order status', 'verbose_name_plural': 'Order statuses'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-end_date'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['code'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='returnreason',
            options={'ordering': ['code'], 'verbose_name': 'Return reason', 'verbose_name_plural': 'Return reasons'},
        ),
        migrations.AlterModelOptions(
            name='returnrequeststatus',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Return request status', 'verbose_name_plural': 'Return request statuses'},
        ),
        migrations.AlterModelOptions(
            name='returntype',
            options={'ordering': ['code'], 'verbose_name': 'Return type', 'verbose_name_plural': 'Return types'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name_en'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['code'], 'verbose_name': 'Tax rate', 'verbose_name_plural': 'Tax rates'},
        ),
        migrations.AlterModelOptions(
            name='township',
            options={'ordering': ['region', 'name_en'], 'verbose_name': 'Township', 'verbose_name_plural': 'Townships'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['code'], 'verbose_name': 'Unit of measure', 'verbose_name_plural': 'Units of measure'},
        ),
        migrations.AddField(
            model_name='companysetting',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings', to='master_data.region'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings', to='master_data.township'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_settings', to='master_data.currency'),
        ),
    ]
