# Generated by Django 4.2.7 on 2026-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_contacttype_deleted_at_currency_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='master_data_is_acti_6dc1fe_idx'),
        ),
    ]
