# Generated by Django 4.2.7 on 2026-02-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_alter_country_options_country_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='default_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings', to='master_data.country', verbose_name='Default Country'),
        ),
    ]
