# Generated by Django 4.2.7 on 2026-02-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_companysetting_default_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Shop name'),
        ),
    ]
