# Generated by Django 4.2.7 on 2026-02-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_companysetting_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='Notes')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to='master_data.supplier')),
            ],
            options={
                'verbose_name': 'Supplier phone number',
                'verbose_name_plural': 'Supplier phone numbers',
            },
        ),
    ]
