# Generated by Django 4.2.7 on 2026-02-04 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productpricetier_customer_type_and_more'),
        ('customers', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'အမှာစာအသေးစိတ်', 'verbose_name_plural': 'အမှာစာအသေးစိတ်များ'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'ငွေချေပြီးပြီးမှု', 'verbose_name_plural': 'ငွေချေပြီးပြီးမှုများ'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'အမှာစာ', 'verbose_name_plural': 'အမှာစာများ'},
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='orders_sale_custome_56befd_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='orders_sale_status__5826e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesorder',
            name='orders_sale_created_e7f654_idx',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reconciled_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='စုစုပေါင်း'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='မှတ်ချက်'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ငွေရက်'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='ရည်ညွှန်းအမှတ်'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='မှတ်တမ်းတင်သူ'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='ပို့ဆောင်ရက်'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='အမှာစာရက်'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ငွေပြီးပြီးပမား'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder', verbose_name='အမှာစာ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='ပစ္စည်း'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='အရေအတွက်'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ယူနစ်စျေး'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ပမားရက်ပမား'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.salesorder', verbose_name='အမှာစာ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'ငွေသား'), ('bank_transfer', 'ဘဏ်ခ်ငွေ့ပြောင်း'), ('mobile_banking', 'မိုဘိုင်ဘဏ်ခ်ငွေ'), ('check', 'ချက်လုပ်')], max_length=20, verbose_name='ငွေပြီးပြီးနည်း'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='ဖောက်သည်'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='လျှော့ဈေး'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='မှတ်ချက်'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='အမှာစာအမှတ်'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.orderstatus', verbose_name='အခြေအနေ'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='စုစုပေါင်း'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='စုစုပေါင်းပေးချေရမည်'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
