# Generated by Django 4.2.7 on 2026-02-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_companysetting_deliveryroute_promotion_region_and_more'),
        ('orders', '0002_remove_discount_customer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='applied_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.promotion', verbose_name='ပရိုမိုးရှင်း'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ပို့ဆောင်ခ'),
        ),
    ]
