# Generated by Django 4.2.7 on 2026-02-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0002_companysetting_deliveryroute_promotion_region_and_more'),
        ('orders', '0003_salesorder_applied_promotion_salesorder_delivery_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'ငွေချေပြီးပြီးမှု', 'verbose_name_plural': 'ငွေချေပြီးပြီးမှုများ'},
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ဘောက်ချာနံပါတ်'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.salesorder', verbose_name='အမှာစာ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='master_data.paymentmethod', verbose_name='ငွေပေးချေမှုနည်းလမ်း'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['voucher_number'], name='orders_paym_voucher_89b488_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='orders_paym_payment_9e5ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='orders_paym_payment_22a985_idx'),
        ),
    ]
