# Generated by Django 4.2.7 on 2026-02-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_companysetting_deliveryroute_promotion_region_and_more'),
        ('orders', '0004_alter_payment_options_payment_voucher_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='master_data.paymentmethod', verbose_name='ငွေပေးချေမှုနည်းလမ်း'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ဘောက်ချာနံပါတ်'),
        ),
    ]
