# Generated by Django 4.2.7 on 2026-02-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='order_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PRE_ORDER', 'Pre-order')], default='NORMAL', max_length=20, verbose_name='အမှာစာအမျိုးအစား'),
        ),
    ]
