# Generated by Django 4.2.7 on 2026-02-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['deleted_at'], name='orders_sale_deleted_a69239_idx'),
        ),
    ]
