# Generated by Django 4.2.7 on 2026-02-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_soft_delete_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salesorder',
            name='orders_sale_deleted_a69239_idx',
        ),
    ]
