# Generated by Django 4.2.7 on 2026-02-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_salesorder_orders_sale_deleted_a69239_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['deleted_at'], name='orders_paym_deleted_c0a5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['deleted_at'], name='orders_sale_deleted_a69239_idx'),
        ),
    ]
