# Generated by Django 4.2.7 on 2026-02-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_payment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['delivery_date'], name='orders_sale_deliver_3546bb_idx'),
        ),
    ]
