# Generated by Django 4.2.7 on 2026-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_salesorder_orders_sale_deliver_3546bb_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PRE_ORDER', 'Pre-order'), ('REPLACEMENT', 'Replacement')], default='NORMAL', max_length=20, verbose_name='Order type'),
        ),
    ]
