# Generated by Django 4.2.7 on 2026-02-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'Expense category', 'verbose_name_plural': 'Expense categories'},
        ),
    ]
