# Generated by Django 4.2.7 on 2026-02-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_expense_options_alter_expensecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['deleted_at'], name='accounting__deleted_4a943d_idx'),
        ),
    ]
