# Generated by Django 4.2.7 on 2026-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expense_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='accounting__date_c78dd7_idx'),
        ),
    ]
